### ISSUE TITLE
Design improvements - Mobile First 

### ISSUE THREAD

**Issue by michael-spengler** [michael-spengler/dhbw-richie#4]
Reporter: Jan

**Comment by aaronschweig** [comment]
Als Iconset wurde Fontawesome ausgewählt

**Comment by aaronschweig** [comment]
@Timo Wir brauchen keine Register-Route, da wir alles über OAuth Provider regeln!

**Comment by aaronschweig** [comment]
* Datenschutzerklärung @aaronschweig 
* Impressum @aaronschweig 
* FAQ --> Menschen
* Wer ist DHBWRichie? --> Menschen
* Wer bin ich? --> Menschen

**Comment by michael-spengler** [comment]
Liebe Frontend Entwickler :) 
Das hier könnte insbesondere für Euch interessant sein: https://github.com/michael-spengler/dhbw-richie/issues/11#issuecomment-539721630

Falls Ihr Lust habt könnt Ihr vielleicht schonmal einige zusätzliche steps aus dem steps_file.js einkommentieren und ggf. Euren UI-Elementen entsprechend anpassen.
